-- add more treesitter parsers
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "awk",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "php",
      "twig",
      "css",
      "go",
      "templ",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "xml",
      "ruby",
      "scheme",
      "scss",
      "sql",
      "toml",
    },
    autopairs = {
      enable = true,
    },

    highlight = {
      enable = true, -- This is a MUST
      additional_vim_regex_highlighting = {
        "php",
        "css",
        "scss",
        "c",
        "lua",
        "twig",
        "html",
        "go",
        "templ",
        "javascript",
        "typescript",
      },
    },
    indent = { enable = true, disable = { "python" } },
  },
}
